name: Soft Blue Switch
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e1dfd5e6-8cd5-499b-ae3a-acfa1e4115e9.ico
layout_spectrum: 0
typography_spectrum: 0.9159646476618946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8403706476092339
  lightness: 0.9887405671179295
  saturation: 0.19561750954017043
  rhythmicContrast: 0.9836012034211308
purpose: []
